# Generated by Django 5.0.7 on 2024-08-01 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
