# Generated by Django 5.0.7 on 2024-08-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=65, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=65)),
            ],
        ),
    ]
