# Generated by Django 5.0.7 on 2024-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(default='', max_length=5),
        ),
    ]
